name: Blog | Jim Nielsen, Designer
markdown: redcarpet
highlighter: pygments
baseurl: /blog
imageurl: /blog/assets/img
# imageurl: assets/img # for testing
domain: http://jim-nielsen.com
permalink: /posts/:title
paginate: 5