name: Jim Nielsen’s Blog
baseurl: /blog
imageurl: /blog/assets/img
# imageurl: assets/img # for testing
domain: http://jim-nielsen.com
permalink: /:year/:title/
# permalink: /:short_year:month:day/
sass:
    sass_dir: _sass
gems:
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    disable : true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      type: "post"
